"""Anima LLLite field registry: generated trainer-arg FieldSpecs + GUI-only
bookkeeping fields + the derivation hook (see anima_lllite_derivations.py).

FieldSpecs for the trainer-facing keys are generated by
scripts/gen_anima_lllite_fields.py from the Move 4 gap analysis; regenerate
with `uv run python scripts/gen_anima_lllite_fields.py` after any
gap-analysis change.

Per wargame/reference/arch-matrix-anima_lllite.md #1, this tab is
architecture-fixed -- there is no model-checkbox row, unlike every other
training type in this project. `architecture` is still modeled as a
single-choice dropdown (rather than omitted) so this training type's
registry shape matches the other five and `build_tab`/`build_run_config`
need no training-type-specific branch for "no architecture selector".
"""

from ..fields import FieldRegistry, FieldSpec, Widget
from .anima_lllite_derivations import derive as derive_anima_lllite
from .anima_lllite_fields_generated import ANIMA_LLLITE_FIELDS

ARCHITECTURE_CHOICES = ["anima_lllite"]

GUI_ONLY_FIELDS = [
    FieldSpec(
        name="architecture",
        widget=Widget.DROPDOWN,
        default="anima_lllite",
        choices=ARCHITECTURE_CHOICES,
        label="Architecture",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"anima_lllite"}),
    ),
    FieldSpec(
        name="training_type",
        widget=Widget.TEXTBOX,
        default="anima_lllite",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"anima_lllite"}),
    ),
]

ANIMA_LLLITE_REGISTRY = FieldRegistry(GUI_ONLY_FIELDS + ANIMA_LLLITE_FIELDS)


def derive(values: dict, arch_key: str) -> dict:
    return derive_anima_lllite(values, arch_key)
