"""DreamBooth field registry: generated trainer-arg FieldSpecs + GUI-only
bookkeeping fields + the derivation hook (see dreambooth_derivations.py).

FieldSpecs for the trainer-facing keys are generated by
scripts/gen_dreambooth_fields.py from the Move 4 gap analysis; regenerate
with `uv run python scripts/gen_dreambooth_fields.py` after any gap-analysis
change.

Per wargame/reference/arch-matrix-dreambooth.md #1, this tab supports
exactly 4 architectures (no lumina/anima/hunyuan_image): SD1.x/2.x (default,
`train_db.py`), SDXL, SD3, FLUX.1. `sd15`/`sd2` are modeled as two
architecture keys sharing one script and one gap-analysis section, since
`v2`/`v_parameterization` are plain universal TOML flags that never change
which script runs (matrix line 16).
"""

from ..fields import FieldRegistry, FieldSpec, Widget
from .dreambooth_derivations import derive as derive_dreambooth
from .dreambooth_fields_generated import DREAMBOOTH_FIELDS

ARCHITECTURE_CHOICES = ["sd15", "sd2", "sdxl", "sd3", "flux1"]

GUI_ONLY_FIELDS = [
    FieldSpec(
        name="architecture",
        widget=Widget.DROPDOWN,
        default="sd15",
        choices=ARCHITECTURE_CHOICES,
        label="Architecture",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"dreambooth"}),
    ),
    FieldSpec(
        name="training_type",
        widget=Widget.TEXTBOX,
        default="dreambooth",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"dreambooth"}),
    ),
]

DREAMBOOTH_REGISTRY = FieldRegistry(GUI_ONLY_FIELDS + DREAMBOOTH_FIELDS)


def derive(values: dict, arch_key: str) -> dict:
    return derive_dreambooth(values, arch_key)
