"""Finetune field registry: generated trainer-arg FieldSpecs + GUI-only
bookkeeping fields + the derivation hook (see finetune_derivations.py).

FieldSpecs for the trainer-facing keys are generated by
scripts/gen_finetune_fields.py from the Move 4 gap analysis; regenerate
with `uv run python scripts/gen_finetune_fields.py` after any gap-analysis
change.

Per wargame/reference/arch-matrix-finetune.md #1, this tab supports 6
architectures: base (SD1.x/SD2.x, `fine_tune.py`), sdxl, sd3, flux1, anima,
lumina -- selected via mutually-exclusive checkboxes with `base` as the
fallback when none are set (no separate script per SD1.x vs SD2.x, unlike
DreamBooth's sd15/sd2 split -- v2/v_parameterization are universal flags
here too).
"""

from ..accelerate_launch_fields import accelerate_launch_fields
from ..fields import FieldRegistry, FieldSpec, Widget
from .finetune_derivations import derive as derive_finetune
from .finetune_fields_generated import FINETUNE_FIELDS

ARCHITECTURE_CHOICES = ["base", "sdxl", "sd3", "flux1", "anima", "lumina"]

GUI_ONLY_FIELDS = [
    FieldSpec(
        name="architecture",
        widget=Widget.DROPDOWN,
        default="base",
        choices=ARCHITECTURE_CHOICES,
        label="Architecture",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"finetune"}),
    ),
    FieldSpec(
        name="training_type",
        widget=Widget.TEXTBOX,
        default="finetune",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"finetune"}),
    ),
]

FINETUNE_REGISTRY = FieldRegistry(
    GUI_ONLY_FIELDS + accelerate_launch_fields("finetune") + FINETUNE_FIELDS
)


def derive(values: dict, arch_key: str) -> dict:
    return derive_finetune(values, arch_key)
