"""LeCo field registry: generated trainer-arg FieldSpecs + GUI-only
bookkeeping fields + the derivation hook (see leco_derivations.py).

FieldSpecs for the trainer-facing keys are generated by
scripts/gen_leco_fields.py from the Move 4 gap analysis; regenerate with
`uv run python scripts/gen_leco_fields.py` after any gap-analysis change.

Per wargame/reference/arch-matrix-leco.md #1, this tab supports exactly 2
architectures via a single `sdxl` boolean checkbox: `sd15`/`sd2` (shared
`train_leco.py`) and `sdxl` (`sdxl_train_leco.py`) -- same sd15/sd2-sharing
pattern as DreamBooth.

`prompts_file` carries `required_cli=True` (see fields.py's contract note
below and leco_tab.py's future command construction, per the wargame plan's
Move 5 fix for the confirmed LeCo crash: both `train_leco.py` and
`sdxl_train_leco.py` declare `--prompts_file` as `required=True`, and
argparse's first `parser.parse_args()` call enforces this against literal
sys.argv *before* `--config_file`'s TOML is ever read -- the old GUI only
writes it into the TOML, so every LeCo run from `kohya_gui/leco_gui.py`
currently fails immediately with `SystemExit(2)`. v2 must always emit
`--prompts_file <value>` directly on the command line in addition to the
TOML key.
"""

from ..accelerate_launch_fields import accelerate_launch_fields
from ..fields import FieldRegistry, FieldSpec, Widget
from .leco_derivations import derive as derive_leco
from .leco_fields_generated import LECO_FIELDS

ARCHITECTURE_CHOICES = ["sd15", "sd2", "sdxl"]

GUI_ONLY_FIELDS = [
    FieldSpec(
        name="architecture",
        widget=Widget.DROPDOWN,
        default="sd15",
        choices=ARCHITECTURE_CHOICES,
        label="Architecture",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"leco"}),
    ),
    FieldSpec(
        name="training_type",
        widget=Widget.TEXTBOX,
        default="leco",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"leco"}),
    ),
]

# FieldSpec.name -> True for fields that must ALSO be emitted directly on
# the accelerate-launch command line (not only inside the --config_file
# TOML), per the confirmed LeCo prompts_file crash documented above and in
# the wargame plan (Move 5, checkpoint B5). leco_tab.py's command builder
# must consult this set.
REQUIRED_CLI_FIELDS = frozenset({"prompts_file"})

LECO_REGISTRY = FieldRegistry(
    GUI_ONLY_FIELDS + accelerate_launch_fields("leco") + LECO_FIELDS
)


def derive(values: dict, arch_key: str) -> dict:
    return derive_leco(values, arch_key)
