"""LoRA field registry: generated trainer-arg FieldSpecs + GUI-only
bookkeeping fields + the derivation hook (see lora_derivations.py).

FieldSpecs for the ~247 trainer-facing keys are generated by
scripts/gen_lora_fields.py from the Move 4 gap analysis; regenerate with
`uv run python scripts/gen_lora_fields.py` after any gap-analysis change.
"""

from ..fields import FieldRegistry, FieldSpec, Widget
from .lora_derivations import derive as derive_lora
from .lora_fields_generated import LORA_FIELDS

ARCHITECTURE_CHOICES = [
    "sd15",
    "sd2",
    "sdxl",
    "flux1",
    "sd3",
    "hunyuan_image",
    "anima",
    "lumina",
]

GUI_ONLY_FIELDS = [
    FieldSpec(
        name="architecture",
        widget=Widget.DROPDOWN,
        default="sd15",
        choices=ARCHITECTURE_CHOICES,
        label="Architecture",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"lora"}),
    ),
    FieldSpec(
        name="training_type",
        widget=Widget.TEXTBOX,
        default="lora",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"lora"}),
    ),
]

LORA_REGISTRY = FieldRegistry(GUI_ONLY_FIELDS + LORA_FIELDS)


def derive(values: dict, arch_key: str) -> dict:
    return derive_lora(values, arch_key)
