"""Textual Inversion field registry: generated trainer-arg FieldSpecs +
GUI-only bookkeeping fields + the derivation hook (see
textual_inversion_derivations.py).

FieldSpecs for the trainer-facing keys are generated by
scripts/gen_textual_inversion_fields.py from the Move 4 gap analysis;
regenerate with `uv run python scripts/gen_textual_inversion_fields.py`
after any gap-analysis change.

Per wargame/reference/arch-matrix-textual_inversion.md #1, this tab
supports exactly 2 architectures: `sd_v1v2` (default, non-SDXL,
`train_textual_inversion.py`) and `sdxl` (`sdxl_train_textual_inversion.py`).

`stop_text_encoder_training_pct` is modeled as gui_only=True: it is
preserved in the save/open TOML round-trip (via a JSON-era alias in the old
GUI) but neither trainer script accepts it, so it never reaches the run
config (arch-matrix-textual_inversion.md section 3).
"""

from ..accelerate_launch_fields import accelerate_launch_fields
from ..fields import FieldRegistry, FieldSpec, Widget
from .textual_inversion_derivations import derive as derive_textual_inversion
from .textual_inversion_fields_generated import TEXTUAL_INVERSION_FIELDS

ARCHITECTURE_CHOICES = ["sd_v1v2", "sdxl"]

GUI_ONLY_FIELDS = [
    FieldSpec(
        name="architecture",
        widget=Widget.DROPDOWN,
        default="sd_v1v2",
        choices=ARCHITECTURE_CHOICES,
        label="Architecture",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"textual_inversion"}),
    ),
    FieldSpec(
        name="training_type",
        widget=Widget.TEXTBOX,
        default="textual_inversion",
        gui_only=True,
        group="architecture",
        training_types=frozenset({"textual_inversion"}),
    ),
    FieldSpec(
        name="stop_text_encoder_training_pct",
        widget=Widget.NUMBER,
        default=0,
        gui_only=True,
        group="basic",
        training_types=frozenset({"textual_inversion"}),
    ),
]

TEXTUAL_INVERSION_REGISTRY = FieldRegistry(
    GUI_ONLY_FIELDS
    + accelerate_launch_fields("textual_inversion")
    + TEXTUAL_INVERSION_FIELDS
)


def derive(values: dict, arch_key: str) -> dict:
    return derive_textual_inversion(values, arch_key)
