import os
from typing import Callable
from cuid2 import cuid_wrapper
from fastapi import Depends, FastAPI
from sqlalchemy.orm import Session

from . import models, schemas
from .database import SessionLocal, engine
from .tasks import train_lora_model

models.Base.metadata.create_all(bind=engine)


app = FastAPI()


# Dependency
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


cuid_generator: Callable[[], str] = cuid_wrapper()


@app.post("/model/train")
def create_and_train_model(
    lora_model_data: schemas.LoraModelCreate, db: Session = Depends(get_db)
):
    # Save the model data to your database first
    db_model = models.LoraModel(
        id=cuid_generator(), **lora_model_data.model_dump(exclude={"trainingImageIds"})
    )
    db.add(db_model)
    for image_id in lora_model_data.trainingImageIds:
        # Retrieve or create TrainingImage instances
        training_image = db.query(models.Image).filter_by(id=image_id).first()
        if not training_image:
            training_image = models.Image(id=image_id)  # Add necessary fields
            db.add(training_image)
        db_model.trainingImages.append(training_image)
    db.commit()
    db.refresh(db_model)  # Get the id generated by the database

    # Now, start the training task
    task = train_lora_model.delay(db_model.to_dict())

    return db_model
