"""Layout map for v2 GUI — section / row / label / info per field name.

Generated by scripts/extract_layout_map.py from kohya_gui/class_*.py.
Regenerate: uv run python scripts/extract_layout_map.py
Hand edits to CURATED_CHOICES / HAND rows should be made in the extractor.
"""

from __future__ import annotations

from typing import NamedTuple, Optional


class FieldLayout(NamedTuple):
    section: str  # accordion group key
    row: Optional[str]  # shared key packs fields into gr.Row; None = own line
    label: Optional[str]
    info: Optional[str]


SECTION_ORDER = [
    "model",
    "folders",
    "dataset",
    "basic",
    "network",
    "advanced",
    "samples",
    "huggingface",
    "metadata",
    "accelerate_launch",
]

SECTION_TITLES = {
    "model": "Model",
    "folders": "Folders",
    "dataset": "Dataset",
    "basic": "Basic",
    "network": "Network",
    "advanced": "Advanced",
    "samples": "Samples",
    "huggingface": "HuggingFace",
    "metadata": "Metadata",
    "accelerate_launch": "Accelerate launch",
}

OPEN_BY_DEFAULT = frozenset(
    {
        "basic",
        "folders",
        "model",
    }
)

CURATED_CHOICES: dict[str, list] = {
    "optimizer_type": [
        "AdamW",
        "AdamWScheduleFree",
        "AdamW8bit",
        "Adafactor",
        "bitsandbytes.optim.AdEMAMix8bit",
        "bitsandbytes.optim.PagedAdEMAMix8bit",
        "DAdaptation",
        "DAdaptAdaGrad",
        "DAdaptAdam",
        "DAdaptAdan",
        "DAdaptAdanIP",
        "DAdaptAdamPreprint",
        "DAdaptLion",
        "DAdaptSGD",
        "Lion",
        "Lion8bit",
        "PagedAdamW8bit",
        "PagedAdamW32bit",
        "PagedLion8bit",
        "Prodigy",
        "prodigyplus.ProdigyPlusScheduleFree",
        "pytorch_optimizer.CAME",
        "RAdamScheduleFree",
        "SGDNesterov",
        "SGDNesterov8bit",
        "SGDScheduleFree",
    ],
    "lr_scheduler": [
        "adafactor",
        "constant",
        "constant_with_warmup",
        "cosine",
        "cosine_with_restarts",
        "linear",
        "piecewise_constant",
        "polynomial",
        "cosine_with_min_lr",
        "inverse_sqrt",
        "warmup_stable_decay",
    ],
    "lr_scheduler_type": [
        "",
        "CosineAnnealingLR",
    ],
    "caption_extension": [
        "",
        ".cap",
        ".caption",
        ".txt",
    ],
    # Align with kohya_gui/class_accelerate_launch.py (not train_util's
    # incomplete list which omits "no" and misspells tensorrt as "tensort").
    # Legacy JSON presets almost always store dynamo_backend="no".
    "dynamo_backend": [
        "no",
        "eager",
        "aot_eager",
        "inductor",
        "aot_ts_nvfuser",
        "nvprims_nvfuser",
        "cudagraphs",
        "ofi",
        "fx2trt",
        "onnxrt",
        "tensorrt",
        "ipex",
        "tvm",
    ],
    # Align with kohya_gui/class_advanced_training.py. Argparse only allows
    # [None, 150, 225] (None → 75 token default), but the legacy GUI and every
    # preset stores the explicit 75 choice; without it Gradio rejects open/save.
    "max_token_length": [
        75,
        150,
        225,
    ],
}

# Defaults that must win over argparse introspection (same reason as CURATED_CHOICES).
CURATED_DEFAULTS: dict[str, object] = {
    "dynamo_backend": "no",
    "max_token_length": 75,
}

# Fields that use CURATED_CHOICES and allow typing values not in the list
CURATED_ALLOW_CUSTOM = frozenset(
    {"optimizer_type", "lr_scheduler", "lr_scheduler_type", "caption_extension"}
)

# "file" or "folder" — which native dialog the legacy GUI wires a Browse
# button to for this field (extract_path_fields() in the generator script);
# absent means the legacy GUI has no picker for it either.
PATH_FIELDS: dict[str, str] = {
    "ae": "file",
    "byt5": "file",
    "clip_g": "file",
    "clip_l": "file",
    "conditioning_data_dir": "folder",
    "dataset_config": "file",
    "gemma2": "file",
    "llm_adapter_path": "file",
    "log_tracker_config": "file",
    "logging_dir": "folder",
    "output_dir": "folder",
    "pretrained_model_name_or_path": "file",
    "qwen3": "file",
    "reg_data_dir": "folder",
    "resume": "folder",
    "t5_tokenizer_path": "folder",
    "t5xxl": "file",
    "text_encoder": "file",
    "tokenizer_cache_dir": "folder",
    "train_data_dir": "folder",
    "vae": "file",
}


def path_kind_for(name: str) -> Optional[str]:
    """Return "file", "folder", or None for a field name."""
    return PATH_FIELDS.get(name)


LAYOUT: dict[str, FieldLayout] = {
    "adaptive_noise_scale": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_15",
        label="Adaptive noise scale",
        info="Add `latent mean absolute value * this value` to noise_offset",
    ),
    "additional_parameters": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_3",
        label="Additional parameters",
        info=None,
    ),
    "ae": FieldLayout(
        section="model", row="advanced.class_flux1.row_1", label="VAE Path", info=None
    ),
    "alpha_mask": FieldLayout(section="advanced", row=None, label=None, info=None),
    "anima_checkbox": FieldLayout(
        section="model", row="model.class_source_model.row_8", label="Anima", info=None
    ),
    "apply_lg_attn_mask": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "apply_t5_attn_mask": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_2",
        label="Apply T5 Attention Mask",
        info="Apply attention mask to T5-XXL encode and FLUX double blocks ",
    ),
    "architecture": FieldLayout(section="model", row=None, label=None, info=None),
    "async_upload": FieldLayout(
        section="huggingface",
        row="huggingface.class_huggingface.row_4",
        label="Async upload",
        info=None,
    ),
    "attn_mode": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_4",
        label="Attention Mode",
        info="xformers requires Split Attention. sageattn does not support training (inference only)",
    ),
    "base_weights": FieldLayout(section="network", row=None, label=None, info=None),
    "base_weights_multiplier": FieldLayout(
        section="network", row=None, label=None, info=None
    ),
    "block_alphas": FieldLayout(section="network", row=None, label=None, info=None),
    "block_dims": FieldLayout(section="network", row=None, label=None, info=None),
    "block_lr": FieldLayout(section="advanced", row=None, label=None, info=None),
    "block_lr_zero_threshold": FieldLayout(
        section="network", row=None, label=None, info=None
    ),
    "blocks_to_swap": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_18",
        label="Blocks to swap",
        info="The number of blocks to swap. The default is None (no swap). These options must be combined with --fused_backward_pass or --blockwise_fused_optimizers. The recommended maximum value is 36.",
    ),
    "blockwise_fused_optimizers": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_7",
        label="Blockwise Fused Optimizer",
        info="Enable blockwise optimizers for fused backward pass and optimizer step. Any optimizer can be used.",
    ),
    "bucket_no_upscale": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_12",
        label="Don't upscale bucket resolution",
        info=None,
    ),
    "bucket_reso_steps": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_12",
        label="Bucket resolution steps",
        info=None,
    ),
    "bypass_mode": FieldLayout(section="network", row=None, label=None, info=None),
    "byt5": FieldLayout(
        section="advanced",
        row="advanced.class_hunyuan_image.row_1",
        label="byT5 Path",
        info=None,
    ),
    "cache_info": FieldLayout(section="advanced", row=None, label=None, info=None),
    "cache_latents": FieldLayout(
        section="basic", row="basic.seed_cache", label="Cache latents", info=None
    ),
    "cache_latents_to_disk": FieldLayout(
        section="basic",
        row="basic.seed_cache",
        label="Cache latents to disk",
        info=None,
    ),
    "cache_text_encoder_outputs": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_6",
        label="Cache Text Encoder Outputs",
        info="Cache Qwen3 text encoder outputs to reduce VRAM usage. Recommended when not training Text Encoder LoRA.",
    ),
    "cache_text_encoder_outputs_to_disk": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_6",
        label="Cache Text Encoder Outputs to Disk",
        info="Cache text encoder outputs to disk. Automatically enables Cache Text Encoder Outputs.",
    ),
    "caption_dropout_every_n_epochs": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_18",
        label="Dropout caption every n epochs",
        info=None,
    ),
    "caption_dropout_rate": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_18",
        label="Rate of caption dropout",
        info=None,
    ),
    "caption_extension": FieldLayout(
        section="basic",
        row="basic.class_basic_training.row_1",
        label="Caption file extension",
        info=None,
    ),
    "caption_prefix": FieldLayout(section="dataset", row=None, label=None, info=None),
    "caption_separator": FieldLayout(
        section="dataset", row=None, label=None, info=None
    ),
    "caption_suffix": FieldLayout(section="dataset", row=None, label=None, info=None),
    "caption_tag_dropout_rate": FieldLayout(
        section="dataset", row=None, label=None, info=None
    ),
    "checkpoint_file": FieldLayout(section="model", row=None, label=None, info=None),
    "clip_g": FieldLayout(
        section="model", row="advanced.class_sd3.row_2", label="CLIP-G Path", info=None
    ),
    "clip_g_dropout_rate": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_5",
        label="CLIP-G Dropout Rate",
        info="Dropout rate for CLIP-G encoder",
    ),
    "clip_l": FieldLayout(
        section="model",
        row="advanced.class_flux1.row_1",
        label="CLIP-L Path",
        info=None,
    ),
    "clip_l_dropout_rate": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_5",
        label="CLIP-L Dropout Rate",
        info="Dropout rate for CLIP-L encoder",
    ),
    "clip_skip": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_6",
        label="Clip skip",
        info=None,
    ),
    "color_aug": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_10",
        label="Color augmentation",
        info="Enable weak color augmentation",
    ),
    "compile": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_7",
        label="Per-block Torch Compile",
        info="Enable per-block torch.compile for the DiT (requires Triton). ~20% speedup. Mutually exclusive with Legacy Torch Compile below.",
    ),
    "compile_backend": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_8",
        label="Compile Backend",
        info="torch.compile backend for Per-block Torch Compile",
    ),
    "compile_cache_size_limit": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_9",
        label="Compile Cache Size Limit",
        info="torch._dynamo.config.cache_size_limit for Per-block Torch Compile. 0 uses the PyTorch default; 32 is recommended for multi-resolution datasets.",
    ),
    "compile_dynamic": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_8",
        label="Compile Dynamic Shapes",
        info="Dynamic shapes mode for Per-block Torch Compile. On Windows, 'true' requires the Visual Studio 2022 C++ compiler.",
    ),
    "compile_fullgraph": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_9",
        label="Compile Fullgraph",
        info="Enable fullgraph mode for Per-block Torch Compile. Cannot be used with Split Attention.",
    ),
    "compile_mode": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_8",
        label="Compile Mode",
        info="torch.compile mode for Per-block Torch Compile (default recommended for training)",
    ),
    "cond_emb_dim": FieldLayout(section="advanced", row=None, label=None, info=None),
    "conditioning_data_dir": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "console_log_file": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "console_log_level": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "console_log_simple": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "constrain": FieldLayout(section="network", row=None, label=None, info=None),
    "controlnet_model_name_or_path": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "conv_alpha": FieldLayout(section="network", row=None, label=None, info=None),
    "conv_block_alphas": FieldLayout(
        section="network", row=None, label=None, info=None
    ),
    "conv_block_dims": FieldLayout(section="network", row=None, label=None, info=None),
    "conv_dim": FieldLayout(section="network", row=None, label=None, info=None),
    "cpu_offload_checkpointing": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_3",
        label="CPU Offload Checkpointing",
        info="[Experimental] Enable offloading of tensors to CPU during checkpointing",
    ),
    "cross_attn_lr": FieldLayout(section="advanced", row=None, label=None, info=None),
    "cuda_allow_tf32": FieldLayout(section="advanced", row=None, label=None, info=None),
    "cuda_cudnn_benchmark": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "dataset_class": FieldLayout(section="dataset", row=None, label=None, info=None),
    "dataset_config": FieldLayout(
        section="model",
        row="model.data",
        label="Dataset config file (Optional. Select the toml configuration file to use for the dataset)",
        info="Multi-resolution / duplicate-subset datasets are configured entirely in this TOML file, not via GUI fields. See 'Behavior when there are duplicate subsets': https://github.com/kohya-ss/sd-scripts/blob/main/docs/config_README-en.md#behavior-when-there-are-duplicate-subsets",
    ),
    "dataset_repeats": FieldLayout(section="dataset", row=None, label=None, info=None),
    "debiased_estimation_loss": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_11",
        label="Debiased Estimation loss",
        info="Automates the processing of noise, allowing for faster model fitting, as well as balancing out color issues. Do not use if Min SNR gamma is specified.",
    ),
    "debug_dataset": FieldLayout(section="dataset", row=None, label=None, info=None),
    "decompose_both": FieldLayout(section="network", row=None, label=None, info=None),
    "diffusers_xformers": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "dim_from_weights": FieldLayout(section="network", row=None, label=None, info=None),
    "disable_mmap_load_safetensors": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_6",
        label="Disable mmap load safe tensors",
        info="Disable memory mapping when loading the model's .safetensors in SDXL.",
    ),
    "discrete_flow_shift": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_3",
        label="Discrete Flow Shift",
        info="Timestep distribution shift for rectified flow training, used when Timestep Sampling is 'shift'. Default is 1.0",
    ),
    "dora_wd": FieldLayout(section="network", row=None, label=None, info=None),
    "double_blocks_to_swap": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_6",
        label="Double Blocks to swap (deprecated)",
        info="[Experimental] Sets the number of 'double_blocks' (~640MB) to swap during the forward and backward passes.",
    ),
    "down_lr_weight": FieldLayout(section="network", row=None, label=None, info=None),
    "dynamo_backend": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_2",
        label="Dynamo backend",
        info="The backend to use for the dynamo JIT compiler.",
    ),
    "dynamo_mode": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_2",
        label="Dynamo mode",
        info="Choose a mode to optimize your training with dynamo.",
    ),
    "dynamo_use_dynamic": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_2",
        label="Dynamo use dynamic",
        info="Whether to enable dynamic shape tracing.",
    ),
    "dynamo_use_fullgraph": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_2",
        label="Dynamo use fullgraph",
        info="Whether to use full graph mode for dynamo or it is ok to break model into several subgraphs",
    ),
    "enable_all_linear": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_4",
        label="Enable All Linear",
        info="(Only applicable to 'FLux1 OFT' LoRA) Target all linear connections in the MLP layer. The default is False, which targets only attention.",
    ),
    "enable_bucket": FieldLayout(
        section="basic",
        row="basic.class_basic_training.row_7",
        label="Enable buckets",
        info=None,
    ),
    "enable_scaled_pos_embed": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_6",
        label="Enable Scaled Positional Embeddings",
        info="Enable scaled positional embeddings in the model.",
    ),
    "enable_wildcard": FieldLayout(section="advanced", row=None, label=None, info=None),
    "extra_accelerate_launch_args": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_5",
        label="Extra accelerate launch arguments",
        info="List of extra parameters to pass to accelerate launch",
    ),
    "face_crop_aug_range": FieldLayout(
        section="dataset", row=None, label=None, info=None
    ),
    "factor": FieldLayout(section="network", row=None, label=None, info=None),
    "flip_aug": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_10",
        label="Flip augmentation",
        info="Enable horizontal flip augmentation",
    ),
    "flux1_checkbox": FieldLayout(
        section="model", row="model.class_source_model.row_8", label="Flux.1", info=None
    ),
    "flux_fused_backward_pass": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_7",
        label="Fused Backward Pass",
        info="Enables the fusing of the optimizer step into the backward pass for each parameter.  Only Adafactor optimizer is supported.",
    ),
    "fp16_master_weights_and_gradients": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "fp8_base": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_7",
        label="fp8 base",
        info="Use fp8 for base model",
    ),
    "fp8_base_unet": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_7",
        label="fp8 base unet",
        info="Flux can be trained with fp8, and CLIP-L can be trained with bf16/fp16.",
    ),
    "fp8_scaled": FieldLayout(
        section="advanced",
        row="advanced.class_hunyuan_image.row_3",
        label="FP8 Scaled",
        info="Use scaled fp8 for the DiT model to reduce VRAM usage",
    ),
    "fp8_vl": FieldLayout(
        section="advanced",
        row="advanced.class_hunyuan_image.row_3",
        label="FP8 VLM",
        info="Use fp8 for the Qwen2.5-VL text encoder",
    ),
    "full_bf16": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_7",
        label="Full bf16 training (experimental)",
        info="Required bitsandbytes >= 0.36.0",
    ),
    "full_fp16": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_7",
        label="Full fp16 training (experimental)",
        info=None,
    ),
    "fused_backward_pass": FieldLayout(
        section="advanced",
        row="advanced.class_sdxl_parameters.row_1",
        label="Fused backward pass",
        info="Enable fused backward pass. This option is useful to reduce the GPU memory usage. Can't be used if Fused optimizer groups is > 0. Only AdaFactor is supported",
    ),
    "fused_optimizer_groups": FieldLayout(
        section="advanced",
        row="advanced.class_sdxl_parameters.row_1",
        label="Fused optimizer groups",
        info="Number of optimizer groups to fuse. This option is useful to reduce the GPU memory usage. Can't be used if Fused backward pass is enabled. Since the effect is limited to a certain number, it is recommended to specify 4-10.",
    ),
    "gemma2": FieldLayout(
        section="advanced",
        row="advanced.class_lumina.row_1",
        label="Gemma2 Path",
        info=None,
    ),
    "gemma2_max_token_length": FieldLayout(
        section="advanced",
        row="advanced.class_lumina.row_3",
        label="Gemma2 Max Token Length",
        info="Maximum token length for Gemma2. Backend default is 256 when omitted.",
    ),
    "gpu_ids": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_4",
        label="GPU IDs",
        info=" What GPUs (by id) should be used for training on this machine as a comma-separated list",
    ),
    "gradient_accumulation_steps": FieldLayout(
        section="basic",
        row="advanced.class_advanced_training.row_1",
        label="Gradient accumulation steps",
        info="Number of updates steps to accumulate before performing a backward/update pass",
    ),
    "gradient_checkpointing": FieldLayout(
        section="basic",
        row="advanced.class_advanced_training.row_9",
        label="Gradient checkpointing",
        info=None,
    ),
    "guidance_scale": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_4",
        label="Guidance Scale",
        info="Guidance scale for Flux1",
    ),
    "highvram": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_8",
        label="highvram",
        info="Disable low VRAM optimization. e.g. do not clear CUDA cache after each latent caching (for machines which have bigger VRAM)",
    ),
    "huber_c": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_4",
        label="Huber C",
        info="The huber loss parameter. Only used if one of the huber loss modes (huber or smooth l1) is selected with loss_type",
    ),
    "huber_scale": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_4",
        label="Huber scale",
        info="The Huber loss scale parameter. Only used if one of the huber loss modes (huber or smooth l1) is selected with loss_type.",
    ),
    "huber_schedule": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_4",
        label="Huber schedule",
        info="The type of loss to use and whether it's scheduled based on the timestep",
    ),
    "huggingface_path_in_repo": FieldLayout(
        section="huggingface",
        row="huggingface.class_huggingface.row_3",
        label="Huggingface path in repo",
        info=None,
    ),
    "huggingface_repo_id": FieldLayout(
        section="huggingface",
        row="huggingface.class_huggingface.row_1",
        label="HuggingFace repo id",
        info=None,
    ),
    "huggingface_repo_type": FieldLayout(
        section="huggingface",
        row="huggingface.class_huggingface.row_2",
        label="Huggingface repo type",
        info=None,
    ),
    "huggingface_repo_visibility": FieldLayout(
        section="huggingface",
        row="huggingface.class_huggingface.row_2",
        label="Huggingface repo visibility",
        info=None,
    ),
    "huggingface_token": FieldLayout(
        section="huggingface",
        row="huggingface.class_huggingface.row_1",
        label="Huggingface token",
        info=None,
    ),
    "hunyuan_image_checkbox": FieldLayout(
        section="model",
        row="model.class_source_model.row_8",
        label="HunyuanImage-2.1",
        info=None,
    ),
    "img_attn_dim": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_9",
        label="img_attn_dim",
        info=None,
    ),
    "img_mlp_dim": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_9",
        label="img_mlp_dim",
        info=None,
    ),
    "img_mod_dim": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_9",
        label="img_mod_dim",
        info=None,
    ),
    "in_dims": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_11",
        label="in_dims",
        info="Order: img_in, time_in, vector_in, guidance_in, txt_in. Example applies LoRA to all conditioning layers per the ranks shown.",
    ),
    "in_json": FieldLayout(section="advanced", row=None, label=None, info=None),
    "init_word": FieldLayout(section="advanced", row=None, label=None, info=None),
    "initial_epoch": FieldLayout(section="advanced", row=None, label=None, info=None),
    "initial_step": FieldLayout(section="advanced", row=None, label=None, info=None),
    "ip_noise_gamma": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_17",
        label="IP noise gamma",
        info="enable input perturbation noise. used for regularization. recommended value: around 0.1",
    ),
    "ip_noise_gamma_random_strength": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_17",
        label="IP noise gamma random strength",
        info="Use random strength between 0~ip_noise_gamma for input perturbation noise",
    ),
    "keep_tokens": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_6",
        label="Keep n tokens",
        info=None,
    ),
    "keep_tokens_separator": FieldLayout(
        section="dataset", row=None, label=None, info=None
    ),
    "learning_rate": FieldLayout(
        section="basic",
        row="basic.lr_family",
        label="Learning rate",
        info="Set to 0 to not train the Unet",
    ),
    "learning_rate_te": FieldLayout(section="basic", row=None, label=None, info=None),
    "learning_rate_te1": FieldLayout(section="basic", row=None, label=None, info=None),
    "learning_rate_te2": FieldLayout(section="basic", row=None, label=None, info=None),
    "learning_rate_te3": FieldLayout(section="basic", row=None, label=None, info=None),
    "leco_denoise_guidance_scale": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "lllite_cond_dim": FieldLayout(section="advanced", row=None, label=None, info=None),
    "lllite_cond_in_channels": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "lllite_cond_resblocks": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "lllite_dropout": FieldLayout(section="advanced", row=None, label=None, info=None),
    "lllite_inpaint_masked_input": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "lllite_mlp_dim": FieldLayout(section="advanced", row=None, label=None, info=None),
    "lllite_multiplier": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "lllite_target_layers": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "lllite_use_aspp": FieldLayout(section="advanced", row=None, label=None, info=None),
    "llm_adapter_lr": FieldLayout(section="advanced", row=None, label=None, info=None),
    "llm_adapter_path": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_2",
        label="LLM Adapter Path",
        info="If omitted, the adapter is loaded from the DiT file when the key llm_adapter.out_proj.weight exists",
    ),
    "log_config": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_22",
        label="Log config",
        info="Log training parameter to WANDB",
    ),
    "log_prefix": FieldLayout(section="advanced", row=None, label=None, info=None),
    "log_tracker_config": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_22",
        label="Log tracker config",
        info="Path to tracker config file to use for logging",
    ),
    "log_tracker_name": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_22",
        label="Log tracker name",
        info="Name of tracker to use for logging, default is script-specific default name",
    ),
    "log_with": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_21",
        label="Logging",
        info="Loggers to use, tensorboard will be used as the default.",
    ),
    "logging_dir": FieldLayout(
        section="folders",
        row="folders.logging",
        label="Logging directory (Optional. to enable logging and output Tensorboard log)",
        info=None,
    ),
    "logit_mean": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_1",
        label="Logit Mean",
        info=None,
    ),
    "logit_std": FieldLayout(
        section="advanced", row="advanced.class_sd3.row_1", label="Logit Std", info=None
    ),
    "loraplus_lr_ratio": FieldLayout(
        section="network", row=None, label=None, info=None
    ),
    "loraplus_text_encoder_lr_ratio": FieldLayout(
        section="network", row=None, label=None, info=None
    ),
    "loraplus_unet_lr_ratio": FieldLayout(
        section="network", row=None, label=None, info=None
    ),
    "loss_type": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_4",
        label="Loss type",
        info="The type of loss to use and whether it's scheduled based on the timestep",
    ),
    "lowram": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_8",
        label="lowvram",
        info="Enable low RAM optimization. e.g. load models to VRAM instead of RAM (for machines which have bigger VRAM than RAM such as Colab and Kaggle)",
    ),
    "lr_decay_steps": FieldLayout(section="basic", row=None, label=None, info=None),
    "lr_scheduler": FieldLayout(
        section="basic", row="basic.opt_sched", label="LR Scheduler", info=None
    ),
    "lr_scheduler_args": FieldLayout(
        section="basic",
        row="basic.grad_args",
        label="LR scheduler extra arguments",
        info=None,
    ),
    "lr_scheduler_min_lr_ratio": FieldLayout(
        section="basic", row=None, label=None, info=None
    ),
    "lr_scheduler_num_cycles": FieldLayout(
        section="basic",
        row="basic.class_basic_training.row_6",
        label="LR scheduler num cycles",
        info="Number of restarts for cosine scheduler with restarts",
    ),
    "lr_scheduler_power": FieldLayout(
        section="basic",
        row="basic.class_basic_training.row_6",
        label="LR scheduler power",
        info="Polynomial power for polynomial scheduler",
    ),
    "lr_scheduler_timescale": FieldLayout(
        section="basic", row=None, label=None, info=None
    ),
    "lr_scheduler_type": FieldLayout(
        section="basic",
        row="basic.opt_sched",
        label="LR Scheduler type",
        info="(Optional) custom scheduler module name",
    ),
    "lr_warmup_steps": FieldLayout(
        section="basic", row="basic.lr_family", label="LR warmup steps", info=None
    ),
    "lumina_checkbox": FieldLayout(
        section="model", row="model.class_source_model.row_8", label="Lumina", info=None
    ),
    "main_process_port": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_4",
        label="Main process port",
        info="The port to use to communicate with the machine of rank 0.",
    ),
    "masked_loss": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_10",
        label="Masked loss",
        info="Apply mask for calculating loss. conditioning_data_dir is required for dataset",
    ),
    "max_bucket_reso": FieldLayout(
        section="basic",
        row="basic.class_basic_training.row_7",
        label="Max bucket resolution",
        info="Maximum size in pixel a bucket can be (>= 64)",
    ),
    "max_data_loader_n_workers": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_20",
        label="Max num workers for DataLoader",
        info="Override number of epoch. Default: 0",
    ),
    "max_denoising_steps": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "max_grad_norm": FieldLayout(
        section="basic", row="basic.grad_args", label="Max grad norm", info=None
    ),
    "max_timestep": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_13",
        label="Max Timestep",
        info="Values lower than 1000 will make the model more img2img focussed. 1000 = noise only",
    ),
    "max_token_length": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_6",
        label="Max Token Length",
        info="max token length of text encoder",
    ),
    "max_train_epochs": FieldLayout(
        section="basic",
        row="basic.batch_epoch",
        label="Max train epochs",
        info="training epochs (overrides max_train_steps). 0 = no override",
    ),
    "max_train_steps": FieldLayout(
        section="basic",
        row="basic.batch_epoch",
        label="Max train steps",
        info="Overrides # training steps. 0 = no override",
    ),
    "max_validation_steps": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "mem_eff_attn": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_9",
        label="Memory efficient attention",
        info=None,
    ),
    "mem_eff_save": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_5",
        label="Memory Efficient Save",
        info="[Experimentsl] Enable memory efficient save. We do not recommend using it unless you are familiar with the code.",
    ),
    "metadata_author": FieldLayout(
        section="metadata",
        row="metadata.class_metadata.row_1",
        label="Metadata author",
        info=None,
    ),
    "metadata_description": FieldLayout(
        section="metadata", row=None, label="Metadata description", info=None
    ),
    "metadata_is_negative_embedding": FieldLayout(
        section="metadata", row=None, label=None, info=None
    ),
    "metadata_license": FieldLayout(
        section="metadata",
        row="metadata.class_metadata.row_2",
        label="Metadata license",
        info=None,
    ),
    "metadata_merged_from": FieldLayout(
        section="metadata", row=None, label=None, info=None
    ),
    "metadata_preprocessor": FieldLayout(
        section="metadata", row=None, label=None, info=None
    ),
    "metadata_tags": FieldLayout(
        section="metadata",
        row="metadata.class_metadata.row_2",
        label="Metadata tags",
        info=None,
    ),
    "metadata_thumbnail": FieldLayout(
        section="metadata", row=None, label=None, info=None
    ),
    "metadata_title": FieldLayout(
        section="metadata",
        row="metadata.class_metadata.row_1",
        label="Metadata title",
        info=None,
    ),
    "metadata_trigger_phrase": FieldLayout(
        section="metadata", row=None, label=None, info=None
    ),
    "metadata_usage_hint": FieldLayout(
        section="metadata", row=None, label=None, info=None
    ),
    "mid_lr_weight": FieldLayout(section="network", row=None, label=None, info=None),
    "min_bucket_reso": FieldLayout(
        section="basic",
        row="basic.class_basic_training.row_7",
        label="Min bucket resolution",
        info="Minimum size in pixel a bucket can be (>= 64)",
    ),
    "min_snr_gamma": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_11",
        label="Min SNR gamma",
        info="Recommended value of 5 when used",
    ),
    "min_timestep": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_13",
        label="Min Timestep",
        info="Values greater than 0 will make the model more img2img focussed. 0 = image only",
    ),
    "mixed_precision": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_1",
        label="Mixed precision",
        info="Whether or not to use mixed precision training.",
    ),
    "mlp_lr": FieldLayout(section="advanced", row=None, label=None, info=None),
    "mod_lr": FieldLayout(section="advanced", row=None, label=None, info=None),
    "mode_scale": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_1",
        label="Mode Scale",
        info=None,
    ),
    "model_list": FieldLayout(
        section="model", row="model.class_source_model.row_2", label=None, info=None
    ),
    "model_prediction_type": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_2",
        label="Model Prediction Type",
        info=None,
    ),
    "model_type": FieldLayout(section="advanced", row=None, label=None, info=None),
    "module_dropout": FieldLayout(section="network", row=None, label=None, info=None),
    "multi_gpu": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_3",
        label="Multi GPU",
        info="Whether or not this should launch a distributed GPU training.",
    ),
    "multires_noise_discount": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_16",
        label="Multires noise discount",
        info="Recommended values are 0.8. For LoRAs with small datasets, 0.1-0.3",
    ),
    "multires_noise_iterations": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_16",
        label="Multires noise iterations",
        info="Enable multires noise (recommended values are 6-10)",
    ),
    "network_alpha": FieldLayout(
        section="network", row="network.dim_alpha", label="Network Alpha", info=None
    ),
    "network_args": FieldLayout(
        section="network", row=None, label="Network args", info=None
    ),
    "network_dim": FieldLayout(
        section="network",
        row="network.dim_alpha",
        label="Network Rank (Dimension)",
        info=None,
    ),
    "network_dropout": FieldLayout(
        section="network", row="network.dim_alpha", label="Network dropout", info=None
    ),
    "network_module": FieldLayout(
        section="network", row=None, label="Network module", info=None
    ),
    "network_train_text_encoder_only": FieldLayout(
        section="network", row=None, label="Train text encoder only", info=None
    ),
    "network_train_unet_only": FieldLayout(
        section="network", row=None, label="Train U-Net only", info=None
    ),
    "network_weights": FieldLayout(
        section="network", row=None, label="Network weights", info=None
    ),
    "no_half_vae": FieldLayout(section="advanced", row=None, label=None, info=None),
    "no_metadata": FieldLayout(section="advanced", row=None, label=None, info=None),
    "no_token_padding": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_1",
        label="No token padding",
        info=None,
    ),
    "noise_offset": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_15",
        label="Noise offset",
        info="Recommended values are 0.05 - 0.15",
    ),
    "noise_offset_random_strength": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_15",
        label="Noise offset random strength",
        info="Use random strength between 0~noise_offset for noise offset",
    ),
    "noise_offset_type": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_14",
        label="Noise offset type",
        info=None,
    ),
    "num_cpu_threads_per_process": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_1",
        label="Number of CPU threads per core",
        info="The number of CPU threads per process.",
    ),
    "num_last_block_to_freeze": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "num_machines": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_1",
        label="Number of machines",
        info="The total number of machines used in this training.",
    ),
    "num_processes": FieldLayout(
        section="accelerate_launch",
        row="accelerate_launch.class_accelerate_launch.row_1",
        label="Number of processes",
        info="The total number of processes to be launched in parallel.",
    ),
    "num_vectors_per_token": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "optimizer_args": FieldLayout(
        section="basic",
        row="basic.grad_args",
        label="Optimizer extra arguments",
        info=None,
    ),
    "optimizer_type": FieldLayout(
        section="basic", row="basic.opt_sched", label="Optimizer", info=None
    ),
    "output_dir": FieldLayout(
        section="folders",
        row="folders.paths",
        label="Output directory for trained model",
        info=None,
    ),
    "output_name": FieldLayout(
        section="model",
        row="model.source",
        label="Trained Model output name",
        info=None,
    ),
    "persistent_data_loader_workers": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_9",
        label="Persistent data loader",
        info=None,
    ),
    "pos_emb_random_crop_rate": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_6",
        label="Positional Embedding Random Crop Rate",
        info="Random crop rate for positional embeddings",
    ),
    "pretrained_model_name_or_path": FieldLayout(
        section="model",
        row="model.source",
        label="Pretrained model name or path",
        info=None,
    ),
    "prior_loss_weight": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_2",
        label="Prior loss weight",
        info=None,
    ),
    "prompts_file": FieldLayout(section="advanced", row=None, label=None, info=None),
    "qwen3": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_1",
        label="Qwen3 Path",
        info=None,
    ),
    "qwen3_max_token_length": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_4",
        label="Qwen3 Max Token Length",
        info="Maximum token length for the Qwen3 tokenizer",
    ),
    "qwen_image_vae_2d": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_5",
        label="Qwen-Image VAE 2D",
        info="2D Qwen-Image VAE: ~2x faster encode/decode, ~1/3 peak VRAM for single-image caching. VAE Disable Cache has no effect here (2D VAE has no temporal cache).",
    ),
    "random_crop": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_12",
        label="Random crop instead of center crop",
        info=None,
    ),
    "rank_dropout": FieldLayout(section="network", row=None, label=None, info=None),
    "reg_data_dir": FieldLayout(
        section="folders", row="folders.paths", label=None, info=None
    ),
    "rescaled": FieldLayout(section="network", row=None, label=None, info=None),
    "resize_interpolation": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "resolution": FieldLayout(
        section="basic",
        row="basic.class_basic_training.row_7",
        label="Resolution",
        info=None,
    ),
    "resume": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_20",
        label='Resume from saved training state (path to "last-state" state folder)',
        info="Saved state to resume training from",
    ),
    "resume_from_huggingface": FieldLayout(
        section="huggingface",
        row="huggingface.class_huggingface.row_4",
        label="Resume from huggingface",
        info=None,
    ),
    "sample_at_first": FieldLayout(section="samples", row=None, label=None, info=None),
    "sample_batch_size": FieldLayout(
        section="samples", row=None, label=None, info=None
    ),
    "sample_every_n_epochs": FieldLayout(
        section="samples",
        row="samples.timing",
        label="Sample every n epochs",
        info=None,
    ),
    "sample_every_n_steps": FieldLayout(
        section="samples", row="samples.timing", label="Sample every n steps", info=None
    ),
    "sample_prompts": FieldLayout(
        section="samples",
        row="samples.class_sample_images.row_2",
        label="Sample prompts",
        info="One prompt per line. Flags: --w width, --h height, --d seed, --l cfg scale, --s steps, --n negative. Edit prompt.txt in samples dir to update live.",
    ),
    "sample_sampler": FieldLayout(
        section="samples", row="samples.timing", label="Sample sampler", info=None
    ),
    "save_clip": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_3",
        label="Save CLIP models",
        info=None,
    ),
    "save_every_n_epochs": FieldLayout(
        section="basic", row="basic.batch_epoch", label="Save every N epochs", info=None
    ),
    "save_every_n_steps": FieldLayout(
        section="basic",
        row="advanced.class_advanced_training.row_5",
        label="Save every N steps",
        info="(Optional) The model is saved every specified steps",
    ),
    "save_last_n_epochs": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_5",
        label="Save last N epochs",
        info="(Optional) Save only the specified number of epochs (old epochs will be deleted)",
    ),
    "save_last_n_epochs_state": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_5",
        label="Save last N epochs state",
        info="(Optional) Save only the specified number of epochs states (old models will be deleted)",
    ),
    "save_last_n_steps": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_5",
        label="Save last N steps",
        info="(Optional) Save only the specified number of models (old models will be deleted)",
    ),
    "save_last_n_steps_state": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_5",
        label="Save last N steps state",
        info="(Optional) Save only the specified number of states (old models will be deleted)",
    ),
    "save_model_as": FieldLayout(
        section="model",
        row="model.class_source_model.row_10",
        label="Save trained model as",
        info=None,
    ),
    "save_n_epoch_ratio": FieldLayout(section="basic", row=None, label=None, info=None),
    "save_precision": FieldLayout(
        section="model",
        row="model.class_source_model.row_10",
        label="Save precision",
        info=None,
    ),
    "save_state": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_20",
        label="Save training state",
        info="Save training state (including optimizer states etc.) when saving models",
    ),
    "save_state_on_train_end": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_20",
        label="Save training state at end of training",
        info="Save training state (including optimizer states etc.) on train end",
    ),
    "save_state_to_huggingface": FieldLayout(
        section="huggingface",
        row="huggingface.class_huggingface.row_4",
        label="Save state to huggingface",
        info=None,
    ),
    "save_t5xxl": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_3",
        label="Save T5-XXL model",
        info=None,
    ),
    "scale_v_pred_loss_like_noise_pred": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_11",
        label="Scale v prediction loss",
        info="SD v2 only. Scales loss by timestep so global/local noise prediction weights match; may improve detail.",
    ),
    "scale_weight_norms": FieldLayout(
        section="network", row=None, label=None, info=None
    ),
    "sd3_cache_text_encoder_outputs": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_4",
        label="Cache Text Encoder Outputs",
        info="Cache text encoder outputs to speed up inference",
    ),
    "sd3_cache_text_encoder_outputs_to_disk": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_4",
        label="Cache Text Encoder Outputs to Disk",
        info="Cache text encoder outputs to disk to speed up inference",
    ),
    "sd3_checkbox": FieldLayout(
        section="model", row="model.class_source_model.row_8", label="SD3", info=None
    ),
    "sd3_fused_backward_pass": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_6",
        label="Fused Backward Pass",
        info="Enables the fusing of the optimizer step into the backward pass for each parameter.  Only Adafactor optimizer is supported.",
    ),
    "sd3_text_encoder_batch_size": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_4",
        label="Text Encoder Batch Size",
        info=None,
    ),
    "sdpa": FieldLayout(section="advanced", row=None, label=None, info=None),
    "sdxl_cache_text_encoder_outputs": FieldLayout(
        section="advanced",
        row="advanced.class_sdxl_parameters.row_1",
        label="Cache text encoder outputs",
        info="Cache the outputs of the text encoders. This option is useful to reduce the GPU memory usage. This option cannot be used with options for shuffling or dropping the captions.",
    ),
    "sdxl_checkbox": FieldLayout(
        section="model", row="model.class_source_model.row_8", label="SDXL", info=None
    ),
    "sdxl_no_half_vae": FieldLayout(
        section="advanced",
        row="advanced.class_sdxl_parameters.row_1",
        label="No half VAE",
        info="Disable the half-precision (mixed-precision) VAE. VAE for SDXL seems to produce NaNs in some cases. This option is useful to avoid the NaNs.",
    ),
    "secondary_separator": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "seed": FieldLayout(
        section="basic",
        row="basic.seed_cache",
        label="Seed",
        info="Set to 0 to make random",
    ),
    "self_attn_lr": FieldLayout(section="advanced", row=None, label=None, info=None),
    "show_timesteps": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_19",
        label="Show timesteps",
        info="Visualizes sampled timestep distribution and loss weighting, then exits without training. 'console'=ASCII histogram, 'image'=matplotlib plot. FLUX/SD3 only.",
    ),
    "show_timesteps_resolution": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_19",
        label="Show timesteps resolution",
        info="Image resolution (pixels) assumed by 'Show timesteps' for resolution-dependent sampling (e.g. flux_shift). Comma-separated: a single value is used for both H and W, two values are H,W.",
    ),
    "shuffle_caption": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_9",
        label="Shuffle caption",
        info=None,
    ),
    "sigmoid_scale": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_3",
        label="Sigmoid Scale",
        info='Scale factor for sigmoid timestep sampling (used when Timestep Sampling is "sigmoid", "shift" or "flux_shift")',
    ),
    "single_blocks_to_swap": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_6",
        label="Single Blocks to swap (deprecated)",
        info="[Experimental] Sets the number of 'single_blocks' (~320MB) to swap during the forward and backward passes.",
    ),
    "single_dim": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_9",
        label="single_dim",
        info=None,
    ),
    "single_mod_dim": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_10",
        label="single_mod_dim",
        info=None,
    ),
    "skip_cache_check": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_8",
        label="Skip cache check",
        info="Skip cache check for faster training start",
    ),
    "skip_image_resolution": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "skip_latents_validity_check": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "skip_until_initial_step": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "split_attn": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_5",
        label="Split Attention",
        info="Split attention computation to reduce memory usage. Required when using Attention Mode xformers.",
    ),
    "split_mode": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_3",
        label="Split Mode",
        info="Split mode for Flux1",
    ),
    "split_qkv": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_3",
        label="Split QKV",
        info="Split the projection layers of q/k/v/txt in the attention",
    ),
    "stop_text_encoder_training": FieldLayout(
        section="basic",
        row="basic.class_basic_training.row_7",
        label="Stop TE (% of total steps)",
        info=None,
    ),
    "system_prompt": FieldLayout(
        section="advanced",
        row="advanced.class_lumina.row_3",
        label="System Prompt",
        info=None,
    ),
    "t5_dropout_rate": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_5",
        label="T5 Dropout Rate",
        info="Dropout rate for T5-XXL encoder",
    ),
    "t5_max_token_length": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_4",
        label="T5 Max Token Length",
        info="Maximum token length for the T5 tokenizer",
    ),
    "t5_tokenizer_path": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_2",
        label="T5 Tokenizer Path",
        info="If omitted, uses the bundled tokenizer at configs/t5_old/",
    ),
    "t5xxl": FieldLayout(
        section="model",
        row="advanced.class_flux1.row_1",
        label="T5-XXL Path",
        info=None,
    ),
    "t5xxl_device": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_4",
        label="T5-XXL Device",
        info=None,
    ),
    "t5xxl_dtype": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_4",
        label="T5-XXL Dtype",
        info=None,
    ),
    "t5xxl_max_token_length": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_4",
        label="T5-XXL Max Token Length",
        info="Max token length for T5-XXL",
    ),
    "text_encoder": FieldLayout(
        section="advanced",
        row="advanced.class_hunyuan_image.row_1",
        label="Qwen2.5-VL Path",
        info=None,
    ),
    "text_encoder_batch_size": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "text_encoder_cpu": FieldLayout(
        section="advanced",
        row="advanced.class_hunyuan_image.row_4",
        label="Text Encoder on CPU",
        info="Run the Qwen2.5-VL and byT5 text encoders on CPU to reduce VRAM usage",
    ),
    "text_encoder_lr": FieldLayout(
        section="basic",
        row="basic.lr_family",
        label="Text encoder learning rate",
        info="Set to 0 to not train the Text Encoder",
    ),
    "timestep_sampling": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_3",
        label="Timestep Sampling",
        info=None,
    ),
    "token_string": FieldLayout(section="dataset", row=None, label=None, info=None),
    "token_warmup_min": FieldLayout(section="dataset", row=None, label=None, info=None),
    "token_warmup_step": FieldLayout(
        section="dataset", row=None, label=None, info=None
    ),
    "tokenizer_cache_dir": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "torch_compile": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_7",
        label="Legacy Torch Compile (accelerate dynamo)",
        info="Use the legacy accelerate-dynamo torch.compile path instead of the per-block one. Mutually exclusive with Per-block Torch Compile above.",
    ),
    "train_batch_size": FieldLayout(
        section="basic", row="basic.batch_epoch", label="Train batch size", info=None
    ),
    "train_blocks": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_3",
        label="Train Blocks",
        info=None,
    ),
    "train_data_dir": FieldLayout(
        section="model", row="model.data", label=None, info=None
    ),
    "train_double_block_indices": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_8",
        label="train_double_block_indices",
        info="The indices are specified as a list of integers or a range of integers, like '0,1,5,8' or '0,1,4-5,7' or 'all' or 'none'. The number of double blocks is 19.",
    ),
    "train_inpainting": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "train_norm": FieldLayout(section="network", row=None, label=None, info=None),
    "train_on_input": FieldLayout(section="network", row=None, label=None, info=None),
    "train_single_block_indices": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_8",
        label="train_single_block_indices",
        info="The indices are specified as a list of integers or a range of integers, like '0,1,5,8' or '0,1,4-5,7' or 'all' or 'none'. The number of single blocks is 38.",
    ),
    "train_t5xxl": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_3",
        label="Train T5-XXL",
        info="Train T5-XXL model",
    ),
    "train_text_encoder": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "training_comment": FieldLayout(
        section="model",
        row="model.class_source_model.row_9",
        label="Training comment",
        info=None,
    ),
    "training_shift": FieldLayout(section="advanced", row=None, label=None, info=None),
    "training_type": FieldLayout(section="model", row=None, label=None, info=None),
    "txt_attn_dim": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_10",
        label="txt_attn_dim",
        info=None,
    ),
    "txt_mlp_dim": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_10",
        label="txt_mlp_dim",
        info=None,
    ),
    "txt_mod_dim": FieldLayout(
        section="advanced",
        row="advanced.class_flux1.row_10",
        label="txt_mod_dim",
        info=None,
    ),
    "unet_lr": FieldLayout(
        section="basic", row="basic.lr_family", label="U-Net learning rate", info=None
    ),
    "unit": FieldLayout(section="network", row=None, label=None, info=None),
    "unsloth_offload_checkpointing": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_6",
        label="Unsloth Offload Checkpointing",
        info="Offload activations to CPU RAM using async non-blocking transfers (faster than CPU Offload Checkpointing). Cannot be combined with CPU Offload Checkpointing or Blocks to swap.",
    ),
    "up_lr_weight": FieldLayout(section="network", row=None, label=None, info=None),
    "use_cp": FieldLayout(section="network", row=None, label=None, info=None),
    "use_flash_attn": FieldLayout(
        section="advanced",
        row="advanced.class_lumina.row_4",
        label="Use Flash Attention",
        info="Requires flash-attn package",
    ),
    "use_object_template": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "use_safetensors": FieldLayout(section="advanced", row=None, label=None, info=None),
    "use_sage_attn": FieldLayout(
        section="advanced",
        row="advanced.class_lumina.row_4",
        label="Use Sage Attention",
        info=None,
    ),
    "use_scalar": FieldLayout(section="network", row=None, label=None, info=None),
    "use_style_template": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "use_t5xxl_cache_only": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "use_tucker": FieldLayout(section="network", row=None, label=None, info=None),
    "v2": FieldLayout(
        section="model", row="model.class_source_model.row_8", label="v2", info=None
    ),
    "v_parameterization": FieldLayout(
        section="model",
        row="model.class_source_model.row_8",
        label="v_param",
        info=None,
    ),
    "v_pred_like_loss": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_12",
        label="V Pred like loss",
        info="Recommended value of 0.5 when used",
    ),
    "vae": FieldLayout(
        section="model",
        row="advanced.class_advanced_training.row_2",
        label="VAE (Optional: Path to checkpoint of vae for training)",
        info=None,
    ),
    "vae_batch_size": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_18",
        label="VAE batch size",
        info=None,
    ),
    "vae_chunk_size": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_5",
        label="VAE Chunk Size",
        info="Spatial chunk size for VAE encoding/decoding to reduce memory usage. Must be an even number. 0 means no chunking (default).",
    ),
    "vae_disable_cache": FieldLayout(
        section="advanced",
        row="advanced.class_anima.row_5",
        label="VAE Disable Cache",
        info="Disable internal VAE caching mechanism to reduce memory usage (faster, but differs from official behavior)",
    ),
    "validate_every_n_epochs": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "validate_every_n_steps": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "validation_seed": FieldLayout(section="advanced", row=None, label=None, info=None),
    "validation_split": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
    "wandb_api_key": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_21",
        label="WANDB API Key",
        info="Users can obtain and/or generate an api key in the their user settings on the website: https://wandb.ai/login",
    ),
    "wandb_run_name": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_21",
        label="WANDB run name",
        info="The name of the specific wandb session",
    ),
    "weighted_captions": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_1",
        label="Weighted captions",
        info=None,
    ),
    "weighting_scheme": FieldLayout(
        section="advanced",
        row="advanced.class_sd3.row_1",
        label="Weighting Scheme",
        info=None,
    ),
    "weights": FieldLayout(section="advanced", row=None, label=None, info=None),
    "xformers": FieldLayout(
        section="advanced",
        row="advanced.class_advanced_training.row_10",
        label="CrossAttention",
        info=None,
    ),
    "zero_terminal_snr": FieldLayout(
        section="advanced", row=None, label=None, info=None
    ),
}


def layout_for(name: str) -> FieldLayout:
    """Return layout for a field; unknown names fall back to advanced."""
    if name in LAYOUT:
        return LAYOUT[name]
    return FieldLayout(
        section="advanced",
        row=None,
        label=name.replace("_", " ").capitalize(),
        info=None,
    )
