"""One-off generator: build kohya_gui_v2/tabs/anima_lllite_fields_generated.py
from wargame/reference/gap-analysis-anima_lllite.md (port/defect/gap-candidate)
plus real argparse introspection (widget type, default, choices) for the
Anima LLLite tab's single architecture.

Not part of the shipped package -- a build-time tool, run once (re-run if
the gap analysis changes). Output is a plain, hand-editable Python file.

Same header/row vocabulary as LoRA's gap-analysis file. Unlike every other
training type in this project, this tab is architecture-fixed (single
model family + ControlNet-LLLite adapter, no model-checkbox row) --
FieldSpec.archs is always None (universal) since there is only one
architecture to gate against.
"""

import importlib
import os
import re
import sys

SD_SCRIPTS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "sd-scripts"
)
GAP_FILE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "wargame",
    "reference",
    "gap-analysis-anima_lllite.md",
)

MODULE_NAME = "anima_train_control_net_lllite"

ALWAYS_EXCLUDE = {
    "config_file",
    "output_config",
    "help",
    # Accelerate-launch-only concepts: anima_lllite_gui.py's train_model
    # consumes these directly into the accelerate-launch CLI prefix and
    # never writes them into config_toml_data, even though the real trainer
    # parser also declares dynamo_backend (hence gap-analysis classifies it
    # as a gap-candidate, not a defect). Exposing it as a v2 TOML FieldSpec
    # would collide with the existing accelerate-launch-only GUI parameter
    # of the same name and perturb equivalence (same fix as LeCo, Move 7).
    "dynamo_backend",
    "dynamo_mode",
    "dynamo_use_fullgraph",
    "dynamo_use_dynamic",
    "num_processes",
    "num_machines",
    "num_cpu_threads_per_process",
    "multi_gpu",
    "gpu_ids",
    "main_process_port",
    "extra_accelerate_launch_args",
}

WIDGET_ENUM_IMPORT = "from ..fields import FieldSpec, Widget"

_SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)
from gen_fields_common import (
    action_to_widget_and_default,
    emit_field_spec_line,
)  # noqa: E402


def load_parser(module_name):
    if SD_SCRIPTS_DIR not in sys.path:
        sys.path.insert(0, SD_SCRIPTS_DIR)
    mod = importlib.import_module(module_name)
    return mod.setup_parser()


def parse_gap_file(path):
    """Return {arch_key: {name: (category, disposition)}}."""
    text = open(path, encoding="utf-8").read()
    sections = re.split(r"^## Architecture: (\w+) ", text, flags=re.M)
    result = {}
    for i in range(1, len(sections), 2):
        arch_key = sections[i]
        body = sections[i + 1]
        rows = re.findall(
            r"^\| `([a-zA-Z0-9_]+)` \| ([^|]+?) \| ([^|]+?) \|",
            body,
            flags=re.M,
        )
        result[arch_key] = {
            name: (cat.strip(), disp.strip()) for name, cat, disp in rows
        }
    return result


def main():
    gap = parse_gap_file(GAP_FILE)
    rows = gap["anima_lllite"]

    parser = load_parser(MODULE_NAME)
    actions = {a.dest: a for a in parser._actions if a.dest != "help"}

    key_meta: dict = {}

    for name, (cat, disp) in rows.items():
        if name in ALWAYS_EXCLUDE:
            continue
        if cat.startswith("defect"):
            continue
        if cat == "gap candidate" and disp not in ("expose", "expose-advanced"):
            continue
        if name in actions:
            widget, default_repr, coercer, choices_repr = action_to_widget_and_default(
                actions[name]
            )
            key_meta[name] = (
                widget,
                default_repr,
                coercer,
                choices_repr,
                actions[name],
            )

    lines = []
    lines.append(
        '"""Anima LLLite FieldSpecs -- generated by scripts/gen_anima_lllite_fields.py'
    )
    lines.append(
        "from wargame/reference/gap-analysis-anima_lllite.md + arch-matrix-anima_lllite.md."
    )
    lines.append("")
    lines.append("Regenerate with: uv run python scripts/gen_anima_lllite_fields.py")
    lines.append(
        "Hand edits are fine but will be overwritten on regeneration -- move any"
    )
    lines.append(
        "permanent hand corrections into the generator or a follow-up patch step."
    )
    lines.append('"""')
    lines.append("")
    lines.append(WIDGET_ENUM_IMPORT)
    lines.append("")
    lines.append("def _to_int(v):")
    lines.append('    return int(v) if v not in (None, "") else v')
    lines.append("")
    lines.append("def _to_float(v):")
    lines.append('    return float(v) if v not in (None, "") else v')
    lines.append("")
    lines.append("ANIMA_LLLITE_FIELDS = [")

    for name in sorted(key_meta.keys()):
        widget, default_repr, coercer, choices_repr, action = key_meta[name]
        archs_repr = "None"
        lines.append(
            emit_field_spec_line(
                name,
                widget,
                default_repr,
                coercer,
                choices_repr,
                archs_repr,
                "anima_lllite",
                action=action,
            )
        )
    lines.append("]")
    lines.append("")

    out_dir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "kohya_gui_v2",
        "tabs",
    )
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "anima_lllite_fields_generated.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {len(key_meta)} FieldSpecs to {out_path}")


if __name__ == "__main__":
    main()
